---
- hosts: master
  become: true
  roles:
    - ansible-ufw
  vars:
    ufw_rules:
      - rule: allow
        comment: 'allow incoming connection on 22 TCP'
        to_port: 22
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 80 TCP'
        to_port: 80
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 179 TCP'
        to_port: 179
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 443 TCP'
        to_port: 443
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 2379 TCP'
        to_port: 2379
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 2380 TCP'
        to_port: 2380
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 4149 TCP'
        to_port: 4149
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 4789 UDP'
        to_port: 4789
        protocol: udp
      - rule: allow
        comment: 'allow incoming connection on 5473 TCP'
        to_port: 5473
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 6443 TCP'
        to_port: 6443
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 7443 TCP'
        to_port: 7443
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 7946 TCP'
        to_port: 7946
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 7946 UDP'
        to_port: 7946
        protocol: udp
      - rule: allow
        comment: 'allow incoming connection on 8080 TCP'
        to_port: 8080
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 8443 TCP'
        to_port: 8443
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 9099 TCP'
        to_port: 9099
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10250 TCP'
        to_port: 10250
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10251 TCP'
        to_port: 10251
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10252 TCP'
        to_port: 10252
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10255 TCP'
        to_port: 10255
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10256 TCP'
        to_port: 10256
        protocol: tcp

- hosts: "master"
  become_method: sudo
  become: yes
  gather_facts: yes
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.122.101"  --node-name master --pod-network-cidr=172.16.0.0/12

    - name: create .kube directory
      become: yes
      file:
        path: /home/vmadmin/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vmadmin/.kube/config
        remote_src: yes
        owner: vmadmin
        group: vmadmin

    - name: Update bashrc
      lineinfile:
        dest: /home/vmadmin/.bashrc
        line: "export KUBECONFIG=$HOME/.kube/config"
        owner: vmadmin
        group: vmadmin

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Download custom-resources.yaml Calico
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/custom-resources.yaml
        dest: /home/vmadmin/ansible_kubernetes/custom-resources.yaml
        mode: 0755

    - name: Replace string for 172.16.x.x network
      replace:
        path: /home/vmadmin/ansible_kubernetes/custom-resources.yaml
        regexp: '192.168.0.0'
        replace: '172.16.0.0'

    - name: Install tigera operator
      command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/tigera-operator.yaml

    - name: Create manifest to install Calico
      become_user: vmadmin
      command: kubectl create -f /home/vmadmin/ansible_kubernetes/custom-resources.yaml

    - name: Get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

    - name: Restart Cri-o
      systemd:
        name: crio
        daemon_reload: yes
        state: restarted


    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
