---
- hosts: "workers"
  become: true
  roles:
    - ansible-ufw
  vars:
    ufw_rules:
      - rule: allow
        comment: 'allow incoming connection on 22 TCP'
        to_port: 22
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 179 TCP'
        to_port: 179
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 443 TCP'
        to_port: 443
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 7946 TCP'
        to_port: 7946
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 7946 UDP'
        to_port: 7946
        protocol: udp
      - rule: allow
        comment: 'allow incoming connection on 8443 TCP'
        to_port: 8443
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10250 TCP'
        to_port: 10250
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10251 TCP'
        to_port: 10251
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on 10255 TCP'
        to_port: 10255
        protocol: tcp
      - rule: allow
        comment: 'allow incoming connection on range 30000:32767 TCP'
        to_port: 30000:32767
        protocol: tcp


- hosts: "workers"
  become: yes
  gather_facts: yes

  tasks:
    - name: Install NFS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - nfs-common

    - name: Copy join command from Ansible host to the worker nodes.
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes to the cluster.
      become: yes
      command: sh /tmp/kubernetes_join_command

    - name: Restart Cri-o
      systemd:
        state: restarted
        daemon_reload: yes
        name: crio

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
